FROM lcdm/accy

USER root

ADD nbgrader_config.py /opt/conda/etc/jupyter/nbgrader_config.py

RUN pip install git+https://github.com/EdwardJKim/nbgrader && \
    nbgrader extension install

CMD ["start-singleuser.sh"]

USER $NB_USER
ENV TZ America/Chicago

ENV PYTHONPATH "/home/$NB_USER/.accy/rubric:$PYTHONPATH"

