FROM lcdm/accy

USER root

CMD ["start-singleuser.sh"]

USER data_scientist

RUN mkdir -p /home/$NB_USER/.jupyter/custom
ADD logo.png /home/$NB_USER/.jupyter/custom/logo.png
ADD custom.css /home/$NB_USER/.jupyter/custom/custom.css

ENV PYTHONPATH /home/data_scientist/.info490/rubric
